name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure --with-selinux
      
    - name: Install dependencies
      run: make
