name: Makefile CI

on:
  workflow_dispatch:
env:
  Greeting: ${{ secrets.GREETING }}
      
jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - name: Print Hi
      run: echo "$Greeting, have a great build"
      
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure --with-selinux
      
    - name: Install dependencies
      run: make
      
    - name: Install Jfrog CLI
    - uses: jfrog/setup-jfrog-cli@v3
      env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: "https://www.yahoo.com"
    
          # Basic authentication credentials
          JF_USER: "jungelsman@hotmail.com"
          JF_PASSWORD: "password"
    - run: |
        jf --version
