name: Makefile CI

on:
  workflow_dispatch:
env:
  Greeting: "Hi Glen"
      
jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - name: Print Hi
      run: echo "$Greeting, have a great build"
      
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure --with-selinux
      
    - name: Install dependencies
      run: make
