name: Makefile CI

on:
  workflow_dispatch:
env:
  Greeting: ${{ secrets.GREETING }}
      
jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - name: Print Hi
      run: echo "$Greeting, have a great build"
      
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure --with-selinux --prefix $(pwd)/install
      
    - name: Make
      run: make
      
    - name: Make Install
      run: make install
      
    - name: Create Zip file
      run: |
        cd $(pwd)/install
        zip -r something.zip ./bin ./lib ./include ./share
      
    - name: Install Jfrog CLI
      uses: jfrog/setup-jfrog-cli@v3
    
    - name: Check JFrog CLI Version
      run: |
        jf --version
